---
title: "Day 4: Matrices"
author: "Jordan Sibley"
format: html
---

## Create matrices in R 

```{r}
# create a sequence of values ----

my_values <- seq(from = 1, to = 10, by =1)

# convert to matrix ----
my_matrix<- matrix(data = my_values, 
                   nrow = 2,
                   ncol = 5, 
                   byrow = TRUE)
#The byrow = true made it go 1-5 on the top row instead of 12 col 1, 34 col 2... as shown without the argument. 
my_matrix
```

## Incorrectly declared matrix sizes 
```{r}
matrix(dat = my_values, nrow = 2, ncol = 3, byrow = TRUE )
# Gives me a warning that the data length is not a multiple of the number of columns, but it will still make a matrix, just excludes values that do not fit. 
```

# Doing math with matrices 

```{r}
# Scalar multiplication of matrix ----
4 * my_matrix

# Create a second matrix ----
my_values2<- seq(from = 21, to = 30, by = 1)
my_matrix2<- matrix(data = my_values2, nrow = 2, byrow = TRUE)

my_matrix2 # Looks good, number are wrapped by rows

# add matrices ----
my_matrix + my_matrix2

# sub matrices ----
my_matrix2 - my_matrix

# dot product (multiplying) of matrices ----
# make a couple of 2x2 matrices 
cats <- matrix(data = c(0, 4, 3, 1), nrow = 2, byrow = TRUE)
dogs <- matrix (data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)

cats %*% dogs 
```


## Leslie matrix 

```{r}
# create the matrix ----
insect_leslie<- matrix(data= c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0),
                       nrow= 3,
                       byrow = TRUE)

#initial starting conditions ----
insect_y0<- c(12000, 700, 500)

# pop at year 1 ----
insect_y1<- insect_leslie %*% insect_y0
# This gives us 300,000 eggs, 2400 larvae, 56 adults at year 1

# Finding the age classes at year 2 ----
insect_y2<- insect_leslie %*% insect_y1
# Year 2 has 33,600 eggs, 60,000 larvae, 192 adults 

# Finding age class at year 3 ----
insect_y3 <- insect_leslie %*% insect_y2
# year 3 has 115,200 eggs, 6720 larvae, 4,800 adults 
```


## Another example 
```{r}
# create the matrix ----
# Adults produce 5000 seeds each year. 10% of seeds produced become seedlings (juveniles), and 6% of seedlings go on to become adults. 95% of adult trees survive each year.

tree_rep <- matrix(data = c(0, 0, 5000, 0.1, 0, 0, 0, 0.06, 0.95),
                   nrow = 3,
                   byrow = TRUE)

# initial conditions ----
#  5000 seeds, 0 juveniles, and 0 adults
tree_y0<- c(5000, 0, 0)

# pop at year 1 ----
tree_y1<- tree_rep %*% tree_y0
# 0, 500, 0

# pop at year 2 ----
tree_y2<- tree_rep %*% tree_y1
# 0, 0, 30 

# pop at year 3 ----
tree_y3<- tree_rep %*% tree_y2
#150,000, 0, 28.5
```


